[[bond]]
source = "tpknam1qz3pdmtypg8nr8wgj6896jd7qw2grnrnl9e8540hvtaglmdhkyjy5twwhcq"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "81"

[bond.signatures]
tpknam1qz3pdmtypg8nr8wgj6896jd7qw2grnrnl9e8540hvtaglmdhkyjy5twwhcq = "signam1qq3vpe57gsakdylc6qhmmqr8e2ehs99ncuje743yay5fd7vm2jf7arhzc4wt24mehm8tag2tcp6fnnhzj5sk2t360ktqykjxw6z6zrstgh070d"


[[bond]]
source = "tpknam1qz3pdmtypg8nr8wgj6896jd7qw2grnrnl9e8540hvtaglmdhkyjy5twwhcq"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "20"

[bond.signatures]
tpknam1qz3pdmtypg8nr8wgj6896jd7qw2grnrnl9e8540hvtaglmdhkyjy5twwhcq = "signam1qrwt0x9j0vu8ymfh0mf68493uf9l8s8gw9z0ae6dcl52futfwwzrx8v0r835mgclayjwhpqsr5uf202zffsp45ry3l39ftzf2peyq9cvv9ehr5"
